name: fractal
description: Fractal MVP
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  fluttertoast: ^8.0.9
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  http: 0.13.3
  country_code_picker: ^2.0.2
  pinput: ^2.2.6
  firebase_database: ^9.0.9
  syncfusion_flutter_charts: ^20.1.47
  o_color_picker: ^1.0.2
  step_progress_indicator: ^1.0.2
  percent_indicator: ^4.0.0
  flutter_local_notifications: ^9.4.0
  app_state: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - files/
    - images/
    - fonts/
